name = "guess-song-game-api"
main = "worker.js"
compatibility_date = "2026-08-20"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
